#!/usr/bin/bash
#SHELL_FOLDER=$(cd "$(dirname "$0")";pwd)
SHELL_FOLDER=$(env | grep solr | sed 's/solrpoc=//')
#echo $SHELL_FOLDER


#RUN
python3 $SHELL_FOLDER/cve-2018-7600.py <url>:<port>
python3 $SHELL_FOLDER/cve-2019-6430.py <url>:<port>
